controller:
  nginxplus: true
  image:
    repository: nginx-plus-ingress
    tag: "1.5.4-wallarm-r1"
    pullPolicy: IfNotPresent
  wallarm:
    enabled: true
    token: ""
    imagePullSecrets:
    - name: my-secret
