apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-plus-ingress-rc
  labels:
    app: nginx-plus-ingress
spec:
  replicas: 1
  selector:
    app: nginx-plus-ingress
  template:
    metadata:
      labels:
        app: nginx-plus-ingress
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx-plus-ingress:edge
        imagePullPolicy: Always
        name: nginx-plus-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 8080
          hostPort: 8080
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
        args:
          - -nginx-plus
         #- -v=3
         #- -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
