apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: {{ .Values.controller.name | trunc 63 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{- if .Values.controller.wallarm.enabled }}
  enable-wallarm: "true"
{{- end }}
{{- if .Values.controller.config.entries }}
{{ toYaml .Values.controller.config.entries | indent 2 }}
{{- end }}
