{{ if not .Values.controller.defaultTLS.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: default-server-secret
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.controller.defaultTLS.cert }}
  tls.key: {{ .Values.controller.defaultTLS.key }}
{{- end }}
